#!/usr/bin/sh

dialog=$(echo "[Cancel]\nLogout\nReboot\nShutdown\nSuspend" | dmenu -i -b -nb '#151617' -nf '#d8d8d8' -sb '#d8d8d8' -sf '#151617')
if [[ $dialog = "Logout" ]]; then
	openbox --exit
elif [[ $dialog = "Reboot" ]]; then
	systemctl reboot
elif [[ $dialog = "Shutdown" ]]; then
	systemctl poweroff
elif [[ $dialog = "Suspend" ]]; then
	systemctl suspend
fi
