#!/usr/bin/env bash

if ! . cbpp-include.cfg 2>/dev/null; then
        echo '  Failed to locate cbpp-include.cfg in PATH' >&2
        exit 1
fi

connectiontest() {
    local TEXT_CHECKING='Checking internet connection...'
    local TEXT_FAILED='Internet connection test failed!'
    local TEXT_ABORT='Script aborted.'
    local TEXT_OK='Internet connection test passed!'

    local -i i attempts=${1-0}
    for ((i = 0; i < attempts || attempts == 0; i++)); do
        say "$TEXT_CHECKING"
        if wget -O - 'http://ftp.debian.org/debian/README' &>/dev/null; then
            say "$TEXT_OK" 1
            return 0
        fi
        say "$TEXT_FAILED" 1
        if ((i == attempts)); then # if last attempt
            say "$TEXT_ABORT"
            ((attempts == 1)) && return 1 || exit 1
        fi
        clear
    done
}
connectiontest

extra() {
    which pacman >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        clear
        curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/arch-linux-base-setup/main/arch-linux-base-setup.sh >arch-linux-base-setup.sh &&
            chmod 755 arch-linux-base-setup.sh &&
            ./arch-linux-base-setup.sh
    else
        clear
        curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/ubuntu-base-setup/main/ubuntu-base-setup.sh >ubuntu-base-setup.sh &&
            chmod 755 ubuntu-base-setup.sh &&
            ./ubuntu-base-setup.sh
    fi
}

cd /tmp

final() {

    sleep 0.3 && clear
    echo -e "
###############################################################################
# WELCOME! Would you like to run the author's post-installation?(highly recommended)
###############################################################################"

    read -p $'yes/no >_: ' noc
    if [[ "$noc" == "yes" ]]; then
        echo -e "RUNNING ..."
        extra
    elif [[ "$noc" == "no" ]]; then
        echo -e "LEAVING ..."
        return 0
    else
        echo -e "INVALID VALUE!"
        final
    fi
}
final

if [[ $1 = '--firstrun' ]]; then # First run
    [[ -d /live/overlay || ! $(groups) =~ ( |^)sudo( |$) ]] && exit 1
    kitty 'cbpp-welcome'
fi

sudo sed -i -e 's/^(sleep 6s && cbpp-welcome --firstrun) &/##/' $HOME/.config/openbox/autostart
sudo sed -i -e 's/^(sleep 6s && cbpp-welcome --firstrun) &/##/' /etc/skel/.config/openbox/autostart
sudo sed -i -e 's/^(sleep 6s && cbpp-welcome --firstrun) &/##/' /root/.config/openbox/autostart

sudo mkdir /usr/share/fonts/truetype/roboto
 mkdir /home/$USER/Public
 mkdir /home/$USER/backup
 mkdir /home/$USER/Documents
 mkdir /home/$USER/Downloads
 mkdir /home/$USER/Pictures
 mkdir /home/$USER/Music
 mkdir /home/$USER/Videos
sudo chown -R $USER:$USER /home/$USER

sudo wget -P /usr/share/fonts/truetype/roboto/ https://github.com/adi1090x/kitty-cat/raw/master/fonts/Roboto.ttf
(sleep 16s && killall -u $USER) &
curl -fL https://get.oh-my.fish | fish
