#!/usr/bin/env bash
# cbpp-xcompmgr
# Openbox Pipe Menu for use with xcompmgr compositor
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough <corenominal@corenominal.org>
# Ported to #!++ <https://crunchbangplusplus.org>
# by Ben Young <computermouth@crunchbangplusplus.org>

if ! . cbpp-include.cfg 2>/dev/null; then
    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
    exit 1
fi

RESTART_ATTEMPTS=20
# Edit xcompmgr settings
EXECXCOMP='xcompmgr'
if [[ $1 = '--toggle' || $1 = '--start' ]]; then # Toggle compositing with xcompmgr.
    # TODO why --toggle and --start act exactly the same?
    if ! pidof xcompmgr >/dev/null; then
        $EXECXCOMP -a &
    else
        killall xcompmgr
    fi
elif [[ $1 = '--restart' ]]; then
    killall -q xcompmgr
    for ((i = 0; i < RESTART_ATTEMPTS; i++)); do
        pidof xcompmgr >/dev/null || # no process found! Safe to start again
            break

        ((i == RESTART_ATTEMPTS - 1)) && # still didn't die? Probably hangs. Force it to die!
            killall -q -S KILL xcompmgr

        sleep 0.25
    done
    cbpp-compositor --start
else
    # Output Openbox menu
    menuStart
    if ! pidof xcompmgr >/dev/null; then
        menuItem 'Enable Compositing' 'cbpp-compositor --start'
    else
        menuItem 'Restart Compositing' 'cbpp-compositor --restart'
        menuItem 'Disable Compositing' 'cbpp-compositor --toggle'
    fi
    menuEnd
fi
exit 0
