#!/usr/bin/env bash
# cbpp-compton
# Openbox Pipe Menu for use with compton compositor
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough <corenominal@corenominal.org>
# Ported to #!++ <https://crunchbangplusplus.org>
# by Ben Young <computermouth@crunchbangplusplus.org>

RESTART_ATTEMPTS=20
# Edit xcompmgr settings
if [[ $1 = '--edit' ]]; then
    [[ ! -f $HOME/.config/compton.conf ]] &&
        cp '/etc/xdg/compton.conf' "$HOME/.config/compton.conf"

    if [[ -x /usr/bin/kitty ]]; then
        cbpp-gksudo kitty nano $HOME/.config/compton.conf
    else
        featherpad "$HOME/.config/compton.conf" &
    fi
elif [[ $1 = '--toggle' || $1 = '--start' ]]; then # Toggle compositing with compton.
    # TODO why --toggle and --start act exactly the same?
    if ! pidof compton >/dev/null; then
        $EXECXCOMP &
    else
        killall compton
    fi
elif [[ $1 = '--restart' ]]; then
    killall -q compton
    for ((i = 0; i < RESTART_ATTEMPTS; i++)); do
        pidof compton >/dev/null || # no process found! Safe to start again
            break

        ((i == RESTART_ATTEMPTS - 1)) && # still didn't die? Probably hangs. Force it to die!
            killall -q -S KILL compton

        sleep 0.25
    done
    cbpp-compositor --start
elif [[ $1 = '--watch' ]]; then
    while inotifywait -e modify "$HOME/.config/compton.conf"; do
        cbpp-compositor --restart # TODO move this to function?
    done
else
    # Output Openbox menu
    menuStart
    if ! pidof compton >/dev/null; then
        menuItem 'Enable Compositing' 'cbpp-compositor --start'
    else
        menuItem 'Restart Compositing' 'cbpp-compositor --restart'
        menuItem 'Disable Compositing' 'cbpp-compositor --toggle'
        menuSeparator
    fi
    menuItem 'Edit Compositing Settings' 'cbpp-compositor --edit'
    menuEnd
fi
exit 0
