#!/bin/bash

dialog=$(echo -e "[Cancel]\nLogout\nReboot\nShutdown\nSuspend" | dmenu -i)
if [[ $dialog = "Logout" ]]; then
	openbox --exit
elif [[ $dialog = "Reboot" ]]; then
	systemctl reboot
elif [[ $dialog = "Shutdown" ]]; then
	systemctl poweroff
elif [[ $dialog = "Suspend" ]]; then
	xscreensaver-command -lock
	systemctl suspend
fi
