#!/usr/bin/env bash

[[ -d /live/overlay || ! $(groups) =~ ( |^)sudo( |$) ]] && exit 1
if ! . cbpp-include.cfg 2>/dev/null; then
    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
    exit 1
fi

connectiontest() {
    local TEXT_CHECKING='Checking internet connection...'
    local TEXT_FAILED='Internet connection test failed!'
    local TEXT_ABORT='Script aborted.'
    local TEXT_OK='Internet connection test passed!'

    local -i i attempts=${1-0}

    for ((i = 0; i < attempts || attempts == 0; i++)); do
        say "$TEXT_CHECKING"
        if wget -O - 'http://ftp.debian.org/debian/README' &>/dev/null; then
            say "$TEXT_OK" 1
            return 0
        fi
        say "$TEXT_FAILED" 1
        if ((i == attempts)); then # if last attempt
            say "$TEXT_ABORT"
            ((attempts == 1)) && return 1 || exit 1
        fi
        clear
    done
}
sleep 6s
connectiontest

postinstall() {
    sudo apt update &&
        sudo apt install -fy 9base curl git kitty nano network-manager procps psmisc systemd vim xorg &&
        sudo apt install -fy software-properties-common &&
        sudo apt install -fy --no-install-recommends kubuntu-restricted-extras kubuntu-restricted-addons

    PKGS=(
        # --- Importants

        'arandr'               # Provide a simple visual front end for XRandR
        'engrampa'             # Archive manipulator for MATE
        'mate-power-manager'   # MATE Power Manager
        'mksh'                 # MirBSD Korn Shell
        'suckless-tools'       # Simple commands for minimalistic window managers
        'gmrun'                # A lightweight application launcher
        'gsimplecal'           # A simple, lightweight calendar
        'conky'                # A system monitor software for the X Window System
        'dunst'                # Customizable and lightweight notification-daemon
        'featherpad'           # Lightweight Qt plain text editor
        'openbox'              # A lightweight, powerful, and highly configurable stacking window manager
        'scrot'                # Simple command-line screenshot utility
        'pcmanfm-qt'           # The LXQt file manager
        'ranger'               # A file manager with vi key bindings written in python but with an interface that rocks
        'simplescreenrecorder' # A feature-rich screen recorder that supports X11 and OpenGL
        'tint2'                # A simple, unobtrusive and light panel for Xorg
        'xwallpaper'           # A lightweight and simple desktop background setter for X Window
        'xcompmgr'             # A simple composite manager
        'lxappearance'         # Set System Themes
        'lxpolkit'             # LXDE PolicyKit authentication agent
        #'lxdm'                 # A lightweight display manager

        # --- Network

        'gigolo'           # Frontend to manage connections to remote filesystems
        'irssi'            # Text Based IRC
        'transmission-gtk' # BitTorrent client

        # GENERAL UTILITIES ---------------------------------------------------

        'nocache'  # Minimize caching effects
        'powertop' # A tool to diagnose issues with power consumption and power management
        'preload'  # Makes applications run faster by prefetching binaries and shared objects

        # DEVELOPMENT ---------------------------------------------------------

        # (Empty)

        # --- Audio

        'alsaplayer-common' # A heavily multi-threaded PCM player
        'pasystray'         # PulseAudio System Tray
        'playerctl'         # Utility to control media players via MPRIS
        'pulsemixer'        # CLI and curses mixer for PulseAudio

        # --- Bluetooth

        'blueman' # GTK+ Bluetooth Manager

        # TERMINAL UTILITIES --------------------------------------------------

        'fish' # The friendly interactive shell
        'htop' # Interactive process viewer

        # GRAPHICS, VIDEO AND DESIGN ------------------------------------------

        'pinta'    # A simplified alternative to GIMP
        'viewnior' # A simple, fast and elegant image viewer
        'vlc'      # A free and open source cross-platform multimedia player and framework

        # PRINTING ------------------------------------------------------------

        'abiword'               # Fully-featured word processor
        'atril'                 # PDF viewer
        'cups'                  # The CUPS Printing System - daemon package
        'gnumeric'              # A powerful spreadsheet application
        'system-config-printer' # A CUPS printer configuration tool and status applet

    )

    for PKG in "${PKGS[@]}"; do
        echo -e "INSTALLING: ${PKG}"
        sudo apt install -fy --no-install-recommends "$PKG"
    done

    echo -e "Done!"

    echo -e "Disable bluez daemon(opt-out)"
    sudo systemctl disable --now bluetooth.service

    echo -e "Disable cups daemon(opt-out)"
    sudo systemctl disable --now cups.service

    echo -e "Purge unneccasary packages"
    sudo apt-get remove -y --purge apport mailutils clipit compton evince at avahi-daemon avahi-utils geany gimp hexchat dovecot nfs-kernel-server autofs \
        nfs-common evolution rsh-client rsh-redone-client snmp talk telnetd inetutils-telnetd zeitgeist-core zeitgeist-datahub zeitgeist galculator geary \
        ldap-utils mate-media minetest pure-ftpd file-roller xinetd catfish obconf terminator thunar thunar-data xfce4-power-manager xfburn xfce4-notifyd \
        deja-dup nis nitrogen samba-common gstreamer1.0-fluendo-mp3 rhythmbox rpcbind shotwell thunderbird xfce4-screenshooter xfconf mousepad filezilla \
        ibus libreoffice libreoffice-base-core libreoffice-core obsession pavucontrol udiskie xfce4-goodies xscreensaver xtightvncviewer
    sudo apt-mark hold apport
    echo -e "Remove snapd and flatpak garbages"
    sudo systemctl disable --now snapd
    sudo umount /run/snap/ns
    sudo systemctl disable snapd.service
    sudo systemctl disable snapd.socket
    sudo systemctl disable snapd.seeded.service
    sudo systemctl disable snapd.autoimport.service
    sudo systemctl disable snapd.apparmor.service

    sudo rm -f /etc/apparmor.d/usr.lib.snapd.snap-confine.real

    sudo apt-get remove -y --purge snapd
    sudo apt-mark hold snapd

    sudo rm -rfd $HOME/snap
    sudo rm -rfd /snap
    sudo rm -rfd /var/snap
    sudo rm -rfd /var/lib/snapd
    sudo rm -rfd /var/cache/snapd
    sudo rm -rfd /usr/lib/snapd

    flatpak uninstall --all

    sudo apt-get remove -y --purge flatpak
    sudo apt-mark hold flatpak

    # Implement .config/ files of the openbox
    cd /tmp &&
        git clone --branch 11 https://github.com/CBPP/cbpp-icon-theme.git &&
        sudo rm -rfd /usr/share/icons/CBPP
    sudo cp -R cbpp-icon-theme/cbpp-icon-theme/data/usr/share/icons/* /usr/share/icons &&
        git clone --branch 11 https://github.com/CBPP/cbpp-ui-theme.git &&
        sudo rm -rfd /usr/share/themes/CBPP
    sudo cp -R cbpp-ui-theme/cbpp-ui-theme/data/usr/share/themes/* /usr/share/themes &&
        git clone --branch 11 https://github.com/CBPP/cbpp-wallpapers.git &&
    	sudo rm -rfd /usr/share/backgrounds
    sudo mkdir /usr/share/backgrounds
    sudo cp -R cbpp-wallpapers/cbpp-wallpapers/data/usr/share/backgrounds/* /usr/share/backgrounds &&
        git clone --branch 11 https://github.com/CBPP/cbpp-lxdm-theme.git &&
        sudo rm -rfd /usr/share/lxdm/themes/*
    sudo cp -R cbpp-lxdm-theme/cbpp-lxdm-theme/data/etc/lxdm/* /etc/lxdm
    sudo cp -R cbpp-lxdm-theme/cbpp-lxdm-theme/data/usr/share/lxdm/themes/* /usr/share/lxdm/themes
   git clone https://github.com/YurinDoctrine/.config.git &&
        sudo rm -rfd /home/$USER/.config
    sudo rm -rfd /etc/skel/.config
    sudo mkdir /home/$USER/.config
    sudo mkdir /etc/skel/.config
    sudo mkdir /root/.config
    sudo cp -R .config/.conkyrc $HOME
    sudo cp -R .config/.gmrunrc $HOME
    sudo cp -R .config/.gtkrc-2.0 $HOME
    sudo cp -R .config/.gtkrc-2.0.mine $HOME
    sudo cp -R .config/.fonts.conf $HOME
    sudo cp -R .config/.gtk-bookmarks $HOME
    sudo cp -R .config/* $HOME/.config
    sudo cp -R .config/.conkyrc /etc/skel
    sudo cp -R .config/.gmrunrc /etc/skel
    sudo cp -R .config/.gtkrc-2.0 /etc/skel
    sudo cp -R .config/.gtkrc-2.0.mine /etc/skel
    sudo cp -R .config/.fonts.conf /etc/skel
    sudo cp -R .config/.gtk-bookmarks /etc/skel
    sudo cp -R .config/.conkyrc /root
    sudo cp -R .config/.gmrunrc /root
    sudo cp -R .config/.gtkrc-2.0 /root
    sudo cp -R .config/.gtkrc-2.0.mine /root
    sudo cp -R .config/.fonts.conf /root
    sudo cp -R .config/.gtk-bookmarks /root
    sudo cp -R .config/* /etc/skel/.config
    sudo cp -R .config/* /root/.config
    sudo mv /etc/skel/.config/conkywonky /usr/bin
    sudo mv /etc/skel/.config/tint2restart /usr/bin
    sudo mv /etc/skel/.config/cbpp-exit /usr/bin
    sudo mv /etc/skel/.config/cbpp-gksudo /usr/bin
    sudo mv /etc/skel/.config/cbpp-help-pipemenu /usr/bin
    sudo mv /etc/skel/.config/cbpp-compositor /usr/bin
    sudo mv /etc/skel/.config/cbpp-include.cfg /usr/bin
    sudo mv /etc/skel/.config/cbpp-places-pipemenu /usr/bin
    sudo mv /etc/skel/.config/cbpp-recent-files-pipemenu /usr/bin
    sudo mv /etc/skel/.config/cbpp-welcome /usr/bin
    sudo find /home/$USER/.config/ | egrep '\cbpp-' | xargs sudo rm -f
    sudo find /root/.config/ | egrep '\cbpp-' | xargs sudo rm -f
    sudo find /home/$USER/.config/ | egrep '\conkywonky' | xargs sudo rm -f
    sudo find /root/.config/ | egrep '\conkywonky' | xargs sudo rm -f
    sudo find /home/$USER/.config/ | egrep '\tint2restart' | xargs sudo rm -f
    sudo find /root/.config/ | egrep '\tint2restart' | xargs sudo rm -f
}
postinstall

extra() {
    cd /tmp
    clear
    curl -fsSL https://raw.githubusercontent.com/YurinDoctrine/ubuntu-base-setup/main/ubuntu-base-setup.sh >ubuntu-base-setup.sh &&
        chmod 755 ubuntu-base-setup.sh &&
        ./ubuntu-base-setup.sh
}

final() {

    clear
    echo -e "
###############################################################################
# WELCOME! Would you like to run the author's post-installation?(highly recommended)
###############################################################################"

    read -p $'yes/no >_: ' noc
    if [[ "$noc" == "yes" ]]; then
        echo -e "RUNNING ..."
        extra
    elif [[ "$noc" == "no" ]]; then
        echo -e "LEAVING ..."
        return 0
    else
        echo -e "INVALID VALUE!"
        final
    fi
}
final

if [[ $1 = '--firstrun' ]]; then # First run
    kitty cbpp-welcome
fi

USER="$USER"

chsh -s /usr/bin/fish
sudo sed -i -e 's/^(cbpp-welcome --firstrun) &/##/' $HOME/.config/xinitrc
sudo sed -i -e 's/^(cbpp-welcome --firstrun) &/##/' /etc/skel/.config/xinitrc
sudo sed -i -e 's/^(cbpp-welcome --firstrun) &/##/' /root/.config/xinitrc

sudo mkdir /usr/share/fonts/truetype/roboto
 mkdir /home/$USER/Public
 mkdir /home/$USER/Desktop
 mkdir /home/$USER/backup
 mkdir /home/$USER/Documents
 mkdir /home/$USER/Downloads
 mkdir /home/$USER/Pictures
 mkdir /home/$USER/Music
 mkdir /home/$USER/Videos
sudo chown -R $USER:$USER /home/$USER

if [ -f "/home/$USER/.gtk-bookmarks" ]; then
    rpl -q '$USER' $USER /home/$USER/.gtk-bookmarks >/dev/null 2>&1
fi

sudo wget -P /usr/share/fonts/truetype/roboto/ https://github.com/YurinDoctrine/.config/raw/main/kitty/Roboto.ttf
rm -rfd $HOME/.config/kitty/Roboto.ttf

(sleep 16s && killall openbox) &

curl -fL https://get.oh-my.fish | fish
