#!/usr/bin/sh
# conkywonky
# ----------
# Many moons ago, Conky did not automatically restart when changes were
# made to its config files. This script was used to restart it. It does not
# really serve any purpose now, but I like the name and some people may still
# be using/referencing it.

if [ "$(pidof conky)" ]; then
    (killall conky && sleep 0.1 && conky -q) &
    exit 0
else
    conky -q &
    exit 0
fi
