#!/usr/bin/sh
# conkywonky
# ----------
# Many moons ago, Tint2 did not automatically restart when changes were
# made to its config files. This script was used to restart it. It does not
# really serve any purpose now, but I like the name and some people may still
# be using/referencing it.

if [ "$(pidof tint2)" ]; then
    (killall tint2 && sleep 0.1 && tint2) &
    exit 0
else
    tint2 &
    exit 0
fi
